### ISSUE TITLE
docker status Restarting

### ISSUE THREAD

**Issue by wenco** [adriel/denyhosts-docker#4]
hi, i pull docker image from https://hub.docker.com/r/adriel/denyhosts/
and run container, but docker status is Restarting. i need you help！thank you

up logs here:

CentOS Linux release 7.9.2009 (Core) x86-64
Docker version 20.10.8, build 3967b7d

{"log":"    import requests\n","stream":"stderr","time":"2021-08-12T03:13:55.330264568Z"}
{"log":"ImportError: No module named requests\n","stream":"stderr","time":"2021-08-12T03:13:55.330267203Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2021-08-12T03:14:55.731766857Z"}
{"log":"  File \"/usr/bin/denyhosts.py\", line 18, in \u003cmodule\u003e\n","stream":"stderr","time":"2021-08-12T03:14:55.731793927Z"}
{"log":"    from DenyHosts.deny_hosts import DenyHosts\n","stream":"stderr","time":"2021-08-12T03:14:55.731798293Z"}
{"log":"  File \"/usr/lib/python2.7/site-packages/DenyHosts/deny_hosts.py\", line 24, in \u003cmodule\u003e\n","stream":"stderr","time":"2021-08-12T03:14:55.731801527Z"}
{"log":"    from .sync import Sync\n","stream":"stderr","time":"2021-08-12T03:14:55.731808411Z"}
{"log":"  File \"/usr/lib/python2.7/site-packages/DenyHosts/sync.py\", line 6, in \u003cmodule\u003e\n","stream":"stderr","time":"2021-08-12T03:14:55.731811583Z"}
{"log":"    import requests\n","stream":"stderr","time":"2021-08-12T03:14:55.731814796Z"}
{"log":"ImportError: No module named requests\n","stream":"stderr","time":"2021-08-12T03:14:55.731817768Z"}

**Comment by adriel** [comment]
Hmm, yeah it's broken on mine too. I'll look into it tomorrow.

**Comment by adriel** [comment]
Hey, give it another try. I pushed an update that should fix it.

**Comment by wenco** [comment]
yes, container is now running.thankx!
